---
- hosts: all
  become: true
  roles:
    - common
  tasks:
  - name: Create database container with volume
    docker_container:
      name: postgres
      image: postgres:9.5
      state: started
      exposed_ports:
        - 5432
      env:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin
        POSTGRES_DB: example_db
      volumes:
        - /postgres_data:/var/lib/postgresql/data
