---
- name: Create database container with volume
  docker_container:
    name: postgres
    image: postgres:9.5
    state: started
    exposed_ports:
      - 5432
    env:
      POSTGRES_USER: "{{database.user}}"
      POSTGRES_PASSWORD: "{{database.password}}"
    volumes:
      - /postgres_data:/var/lib/postgresql/data
